functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - В верхнем правом углу должена быть кнопка Store, которая возвращает на главную страницу сайта
  - Должна быть возможность переключения языка меню (Английский и Русский)
  - При наведении на кнопку переключения между страницами она должна визуально выделяться (например,
    изменением цвета или появлением тени)
  - При клике на категорию товаров, список товаров должен корректно отображаться в выпадающем меню
  - Список всех брендов-производителей должен отображаться в боковой панели при входе в магазин,
    для удобства навигации