functional:
  - The user should be able to search for products by keyword or category
  - The user should be able to filter products
  - The user should be able to browse products and view detailed product information
  - The user should be able to add products to the cart and view its contents
non-functional:
  - The website must be secure and protect user data
  - The website should be designed with usability in mind and optimized for performance
  - The website must support a mobile version
  - The website must be tested for compatibility with the latest browser versions
  - The website should be able to handle high traffic volumes
  - The website must be accessible on various devices
implicit:
  - A "Store" button must be available in the top-right corner to return to the homepage
  - There must be an option to switch languages (English and Russian)
  - Pagination buttons must highlight on hover (e.g., with color change or shadow)
  - Clicking a product category must properly display the product list in the dropdown menu
  - A list of all brand manufacturers should be displayed in the sidebar when entering the store,
    for easy navigation